---

- hosts: all
  become: True
  any_errors_fatal: True
  roles:
    - role: cluster/ca/prepare

- hosts: master[0]
  become: True
  become_user: cluster-master
  any_errors_fatal: True
  roles:
    - role: cluster/ca/init
