---

- hosts: master
  become: True
  any_errors_fatal: True
  handlers:
    - name: Reload Systemd
      shell: systemctl daemon-reload
    - name: Restart Etcd
      service:
        name: etcd
        state: restarted
  serial: # keep always more than half masters in active mode
    - 1
    - 1
    - 2
    - 3
    - 5
    - 100%
  roles:
    - role: master/etcd
