---

- hosts: all
  become: True
  any_errors_fatal: True
  roles:
    - role: worker/kubernetes/worker.install

- hosts: master[0]
  become: True
  any_errors_fatal: True
  roles:
    - role: worker/kubernetes/worker.add

- hosts: all
  become: True
  any_errors_fatal: True
  handlers:
    - name: Reload Systemd
      shell: systemctl daemon-reload
    - name: Restart CG
      service:
        name: cgconfig
        state: restarted
    - name: Restart Kubelet
      service:
        name: kubelet
        state: restarted
  roles:
    - role: worker/kubernetes/worker.init
