apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
    nauta_release: {{ required "NAUTA Release name is required" .Values.global.nauta }}
    nauta_release_version: {{ required "NAUTA Release version is required" .Values.global.nauta_release }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      release: {{ .Release.Name }}
      chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
      heritage: {{ .Release.Service }}
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 20
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        release: {{ .Release.Name }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        heritage: {{ .Release.Service }}
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      tolerations:
      - key: "master"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "CriticalAddonsOnly"
        operator: "Exists"
      hostNetwork: true
      containers:
      - name: redsocks
        image: {{ required "NAUTA Registry is required" .Values.global.nauta_registry }}/{{ required "NAUTA redsocks image is required" .Values.image }}
        imagePullPolicy: "IfNotPresent"
        securityContext:
          privileged: true
        lifecycle:
          preStop:
            exec:
              command: ["/down.sh"]
        resources:
          limits:
            cpu: 250m
        env:
        - name: IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: SOCKS_IP
          value: '{{ required "SOCKS5 IP is required" .Values.IP }}'
        - name: SOCKS_PORT
          value: '{{ required "SOCKS5 PORT is required" .Values.Port }}'
        - name: INTERFACES
          value: '{{ required "INTERFACES list is required" .Values.Interfaces }}'
        - name: IGNORED_NETWORKS
          value: 10.0.0.0/8
