---

- include_tasks: include_distribution.yml
  vars:
    distribution_file: install.yml

- name: "{{ message_label }} Start and enable cgroup service"
  service:
    name: cgconfig
    state: started
    enabled: True
