apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-tf-push-upgrade
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    nauta_release: {{ required "NAUTA Release name is required" .Values.global.nauta }}
    nauta_release_version: {{ required "NAUTA Release version is required" .Values.global.nauta_release }}
  annotations:
    "helm.sh/hook": "post-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      restartPolicy: Never
      volumes:
        - name: docker
          hostPath:
            path: /var/run/docker.sock
            type: Socket
      containers:
        - name: post-push
          image: {{ required "NAUTA Registry is required" .Values.global.nauta_registry }}/{{ required "NAUTA docker image is required" .Values.docker_image }}
          command:
            - "/push.sh"
            - "{{ .Release.Name }}-registry-nginx"
            - "$(IMAGE)"
            - "cache/$(IMAGE)"
          env:
            - name: IMAGE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}
                  key: image.tensorflow
          volumeMounts:
            - name: docker
              mountPath: /var/run/docker.sock
