---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: runs.aipg.intel.com
spec:
  conversion:
    strategy: None
  group: aipg.intel.com
  names:
    kind: Run
    listKind: RunList
    plural: runs
    shortNames:
      - run
    singular: run
  preserveUnknownFields: true
  scope: Namespaced
  version: v1
  versions:
    - name: v1
      served: true
      storage: true