---

- name: "{{ message_label }} Calculate facts for local deployment"
  set_fact:
    detected_storage_path: "{{ hostvars[master_instance_data].local_data_path | default(master_storage_path) }}"
    detected_storage_selector: "{{ hostvars[master_instance_data].ansible_nodename }}"

- name: "{{ message_label }} Set storage fact"
  set_fact:
    calculated_storage:
      type: "{{ detected_storage_type }}"
      local_path: "{{ detected_storage_path }}"
      local_selector: "{{ detected_storage_selector }}"
