---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ .Release.Name }}-{{ .Chart.Name }}-access"
  labels:
    app: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    kind: view
    {{ .Values.api_group_name }}/view: "true"
rules:
- apiGroups:
    - "*"
  resources:
    - pods/portforward
    - services/portforward
  resourceNames:
    - {{ .Release.Name }}-{{ .Chart.Name }}
    - {{ .Release.Name }}-{{ .Chart.Name }}-defaultbackend
  verbs:
    - get
    - list
    - create
