{{- $token := printf "%s:%s" .Values.global.elasticsearch.admin_username .Values.global.elasticsearch.admin_password -}}
{{- $_ := set . "token" $token }}
apiVersion: v1
kind: Secret
metadata:
  name: es-proxy-auth
  namespace: nauta
type: Opaque
data:
  token: {{ .token | b64enc }}