---

- name: "Set {{ developer_user.key }} presence flag"
  set_fact:
    is_present: "{{ developer_user.value.state | default('present') == 'present' }}"

- name: "Copy {{ developer_user.key }} nctl configuration"
  become: True
  synchronize:
    src: "/usr/local/bin/config"
    dest: "{{ worker_home_prefix }}/{{ developer_user.key }}"
  when: is_present

- name: "Fix {{ developer_user.key }} fresh nctl configuration ownership"
  become: True
  file:
    dest: "{{ worker_home_prefix }}/{{ developer_user.key }}/config"
    owner: "{{ developer_user.key }}"
    group: "{{ worker_groupname }}"
    recurse: True

- name: "Copy {{ developer_user.key }} nctl examples"
  become: True
  synchronize:
    src: "/usr/local/bin/examples"
    dest: "{{ worker_home_prefix }}/{{ developer_user.key }}"
  when: is_present

- name: "Fix {{ developer_user.key }} fresh nctl examples ownership"
  become: True
  file:
    dest: "{{ worker_home_prefix }}/{{ developer_user.key }}/examples"
    owner: "{{ developer_user.key }}"
    group: "{{ worker_groupname }}"
    recurse: True

- name: "Find packs to upgrade with new resource values"
  find:
    paths: "{{ worker_home_prefix }}/{{ developer_user.key }}/config"
    patterns: "values.yaml"
    recurse: True
  register: result
  when: is_present

- name: "Get pool type resources roles"
  set_fact:
    pool_resource_roles: "{{ pack_transition[pool_type | replace ('-', '_')] }}"
  when: is_present and (pool_type | default('')) != ""

- name: "Show resource roles"
  debug:
    msg: "{{ pool_resource_roles }}"
  when: is_present and (pool_type | default('')) != ""

- include_tasks: pack-parametrization.yml
  loop_control:
    loop_var: pack_value_file
  with_items: "{{ result.files }}"
  when: is_present and (pool_type | default('')) != ""

