---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
    nauta_release: {{ required "NAUTA Release name is required" .Values.global.nauta }}
    nauta_release_version: {{ required "NAUTA Release version is required" .Values.global.nauta_release }}
  name: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  ports:
  - port: {{ .Values.buildkitd_port }}
    protocol: TCP
  selector:
    app: {{ .Chart.Name }}
