---

enabled_plugins: []
disabled_plugins: []
use_system_enabled_plugins: False
calculated_enabled_plugins: "{{ enabled_plugins }}"
calculated_disabled_plugins: "{% if use_system_enabled_plugins %}{{ disabled_plugins }}{% else %}*{% endif %}"

enabled_repos: []
disabled_repos: []
use_system_enabled_repos: True
calculated_enabled_repos: "{{ enabled_repos }}"
calculated_disabled_repos: "{% if use_system_enabled_repos %}{{ disabled_repos }}{% else %}*{% endif %}"

nauta_calculated_enabled_repos: "{{ calculated_enabled_repos + ['NAUTARepository'] }}"
