---

# After ansible upgrade from 2.5.5.0 to 2.7.9 emtpy (space) enable_plugin field is a problem.
# For future check.

- name: "{{ message_label }} Install nauta packages {{ packages | join(', ') }} - empty plugin"
  yum:
    disable_plugin: "{{ calculated_disabled_plugins | join(',') }}"
#    enable_plugin: "{{ calculated_enabled_plugins | join(',') }}"
    update_cache: "True"
    disablerepo: "*"
    enablerepo: "NAUTARepository"
    name: "{{ packages }}"
    state: "{{ state | default('present') }}"
  notify: "{{ task_handlers | default([]) }}"
  when: (calculated_enabled_plugins | join(',') | default('') | regex_replace('^\\/|\\/$', '')) == ''

- name: "{{ message_label }} Install nauta packages {{ packages | join(', ') }} - filled plugin"
  yum:
    disable_plugin: "{{ calculated_disabled_plugins | join(',') }}"
    enable_plugin: "{{ calculated_enabled_plugins | join(',') }}"
    update_cache: "True"
    disablerepo: "*"
    enablerepo: "NAUTARepository"
    name: "{{ packages }}"
    state: "{{ state | default('present') }}"
  notify: "{{ task_handlers | default([]) }}"
  when: (calculated_enabled_plugins | join(',') | default('') | regex_replace('^\\/|\\/$', '')) != ''
