---

- name: "{{ message_label }} Ensure remove of {{ packages | join(', ') }}"
  environment: "{{ proxy }}"
  yum:
    disable_plugin: "*"
    update_cache: "False"
    disablerepo: "*"
    name: "{{ packages }}"
    state: "absent"
