---

- name: Run provisioner registry
  hosts: provisioners
  gather_facts: False
  roles:
    - role: fetch-admin

- name: Kill unnecessary workspace pods inside cluster
  hosts: provisioners
  gather_facts: False
  roles:
    - role: workspace-kill
