---

verification_checks:
  - message: "Can not find internal_interface {{ internal_interface }} on host. Found: {{ ansible_interfaces | join(', ') }}"
    condition: "{{ internal_interface not in ansible_interfaces }}"
  - message: "Can not find external_interface {{ external_interface }} on host. Found: {{ ansible_interfaces | join(', ') }}"
    condition: "{{ external_interface not in ansible_interfaces }}"

required_parameters:
  - internal_interface
  - external_interface
