---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ required "NAUTA Release name is required" .Values.global.nauta }}-{{ required "NAUTA Username is required as parameter username" .Values.username }}-namespace-admin"
  labels:
    app: "{{ .Chart.Name }}"
    release: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    heritage: "{{ .Release.Service }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "admin"
subjects:
- kind: ServiceAccount
  name: default
  namespace: "{{ .Release.Namespace }}"
