---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: output-home
  labels:
    app: "{{ .Chart.Name }}"
    release: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    heritage: "{{ .Release.Service }}"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 32Gi
  selector:
    matchLabels:
      app_name: "{{ required "NAUTA Release name is required" .Values.global.nauta }}"
      share: private
      type: output
      user: "{{ required "NAUTA Username is required as parameter user" .Values.username }}"
  storageClassName: ""
