---

- name: Ensure release directories exists
  file:
    path: "{{ build_dir }}/{{ item }}"
    state: directory
  with_items:
    - bin
    - tmp
  notify:
    - Remove build dir

- name: Unarchive input package
  shell: "tar -I pigz -xf {{ package }} ./artifacts"
  args:
    chdir: "{{ build_dir }}/tmp"
  notify:
    - Remove build dir

- name: Synchronize bin dir
  synchronize:
    src: "{{ build_dir }}/tmp/artifacts/"
    dest: "{{ build_dir }}/bin/"

- name: Create package
  shell: tar -cf {{ output }} -I pigz ./
  args:
    chdir: "{{ build_dir }}/bin"
