---

- name: "{{ message_label }} Install package"
  include_tasks: yum_nauta_install.yml
  vars:
    packages:
      - "docker-distribution"
    handlers:
      - Reload Systemd
      - Restart Docker Distribution
