---

- name: Create tar
  shell: tar -cf {{ output }} --use-compress-program=pigz ./
  args:
    chdir: "{{ build_dir }}/data"
  when: create_package | default(True)

- name: Touch file
  file:
    path: "{{ output }}"
    state: touch
  when: not (create_package | default(True))
